In [1]:
import pandas as pd
import numpy as np
import re
import os
from datetime import datetime, timedelta
from sklearn import linear_model as lm
pd.options.mode.chained_assignment = None

In [2]:
def _create_datetime(row):
    """Helper Function

    Parameters
    ----------
    row : TYPE
        Description
    row : pd.Series

    Returns
    -------
    pd.Datetime
    """
    date = row.Datum.strftime("%Y-%m-%d") + " " + row.Uhrzeit
    return date

In [3]:
def read_data_stromfluss(data_dir):
    """Read data from directory, get rid of '-' and NaN values, export a dataframe"""

    dateparse = lambda x: pd.datetime.strptime(x, '%d.%m.%Y')
    numberparse = lambda x: pd.np.float(x.replace(".", "").replace(",", ".")) if x != "-" else np.nan
    convert_thousand = {num: numberparse for num in np.arange(2, 22)}

    import_files = os.listdir(data_dir)

    for i in range(len(import_files)):
        if i == 0:
            df = pd.read_csv(os.path.join(data_dir, import_files[i]), sep=';', decimal=',', thousands='.',
                             parse_dates=['Datum'], date_parser=dateparse, converters=convert_thousand)
        else:
            df = df.append(pd.read_csv(os.path.join(data_dir, import_files[i]), sep=';', decimal=',', thousands='.',
                                       parse_dates=['Datum'], date_parser=dateparse, converters=convert_thousand))

    df.replace('-', 0, inplace=True)
    df.fillna(0, inplace=True)

    return df

In [4]:
def preprocessing_stromfluss(df, basic = False):
    """Preprocessing für Stromfluss Datansatz von Smard

    Parameters
    ----------
    df : pd.DataFrame
        Stromfluss Datensatz von SMARD eingelesen und unbearbeitet

    Returns
    -------
    pd.DataFrame
        Stromfluss Datensatz von SMARD aufbereitet zur weiteren Verwendung
    """

    # Time Formatting
    df["Date"] = df.apply(lambda row: _create_datetime(row), axis=1)
    df["Date"] = pd.to_datetime(df.Date, format="%Y-%m-%d %H:%M")
    df = df.sort_values("Date")

    cols = list(df)
    cols.insert(0, cols.pop(cols.index("Date")))
    df = df.loc[:, cols]

    # Rename columns
    countries = {
        "Niederlande": "NL",
        "Schweiz": "CHE",
        "Dänemark": "DNK",
        "Tschechien": "CZE",
        "Luxemburg": "LUX",
        "Schweden": "SWE",
        "Österreich": "AUT",
        "Frankreich": "FRA",
        "Polen": "PL",
    }

    types = {"Import": "IM", "Export": "EX"}

    type_pattern = r"\((.*?)\)"
    country_pattern = r"(.*?) "

    df.columns = list(df.columns[0:3]) + ['NX'] + [countries.get(re.search(country_pattern, col).group(1))+ "_"+ types.get(re.search(type_pattern, col).group(1)) for col in df.columns[4::]]

    # Netto Export
    df["NX"] = df.iloc[:, 4:].sum(axis = 1)
    
    #Drop columns
    df.drop(df.columns[1:3], axis=1, inplace = True)

    #Export only Datetime and NX for basic analysis
    if basic:
        df = df[['Date', 'NX']]

    return df

In [5]:
df = read_data_stromfluss('data/stromfluss')

In [6]:
df = preprocessing_stromfluss(df, True)

In [7]:
df['Year'] = df['Date'].apply(lambda x: x.year)
df['Month'] = df['Date'].apply(lambda x: x.month)
df['Day'] = df['Date'].apply(lambda x: x.month)
df['Hour'] = df['Date'].apply(lambda x: x.hour)

In [8]:
df.head()

                 Date      NX  Year  Month  Day  Hour
0 2015-06-01 00:00:00  7279.0  2015      6    6     0
1 2015-06-01 01:00:00  7167.0  2015      6    6     1
2 2015-06-01 02:00:00  6667.0  2015      6    6     2
3 2015-06-01 03:00:00  6413.0  2015      6    6     3
4 2015-06-01 04:00:00  5347.0  2015      6    6     4

In [9]:
def predict_validate(model, df, dateList):
    df['NX P'] = np.nan
    df['AE'] = np.nan
    
    if model == 'lm':
        for date in dateList:
            df = predict_lm(df, date)
            
    else:
        print('AA')
        #TBD
    
    return df

In [10]:
def predict_lm(df, date):
    #Train test split
    X = df[df['Date'] < date]
    Y = df[(df['Date'] >= date) & (df['Date'] < date + timedelta(days=1))]
    
    #Train & test
    tmp = lm.LinearRegression().fit(X[['Year', 'Month', 'Day', 'Hour']], X['NX']).predict(Y[['Year', 'Month', 'Day', 'Hour']])
    Y.at[:,'NX P'] = tmp
    #Average error
    Y.at[:,'AE'] = (Y['NX'] - Y['NX P']).apply(lambda x: abs(x))
    
    #Update df with AE information
    df.update(Y)
    
    print('Mean average error for {} is: {}'.format(date, Y['AE'].mean()))
    
    return df

In [11]:
dateList = list()
dateList.append(pd.to_datetime("01/01/2016"))
dateList.append(pd.to_datetime("01/06/2016"))
dateList.append(pd.to_datetime("01/01/2017"))
dateList.append(pd.to_datetime("01/06/2017"))
dateList.append(pd.to_datetime("01/01/2018"))
dateList.append(pd.to_datetime("01/06/2018"))

In [12]:
df_tmp = predict_validate('lm', df, dateList)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/base.py:485: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  linalg.lstsq(X, y)

Mean average error for 2016-01-01 00:00:00 is: 7425.934319841462
Mean average error for 2016-01-06 00:00:00 is: 1412.829451724887
Mean average error for 2017-01-01 00:00:00 is: 2891.2377567407675
Mean average error for 2017-01-06 00:00:00 is: 1006.0989583333334
Mean average error for 2018-01-01 00:00:00 is: 6536.036014853899
Mean average error for 2018-01-06 00:00:00 is: 2063.423776765548

In [13]:
df_tmp[df_tmp['AE'] > 0]

,Date,NX,Year,Month,Day,Hour,NX P,AE
5113,2018-01-01 00:00:00,14551.0,2018.0,1.0,1.0,0.0,6195.075964,8355.924036
5114,2018-01-01 01:00:00,15432.0,2018.0,1.0,1.0,1.0,6150.075964,9281.924036
5115,2018-01-01 02:00:00,15739.0,2018.0,1.0,1.0,2.0,6105.138464,9633.861536
5116,2018-01-01 03:00:00,16078.0,2018.0,1.0,1.0,3.0,6060.138464,10017.861536
5117,2018-01-01 04:00:00,15343.0,2018.0,1.0,1.0,4.0,6015.200964,9327.799036
5118,2018-01-01 05:00:00,15167.0,2018.0,1.0,1.0,5.0,5970.200964,9196.799036
5119,2018-01-01 06:00:00,15281.0,2018.0,1.0,1.0,6.0,5925.263464,9355.736536
5120,2018-01-01 07:00:00,14061.0,2018.0,1.0,1.0,7.0,5880.263464,8180.736536
5121,2018-01-01 08:00:00,13046.0,2018.0,1.0,1.0,8.0,5835.263464,7210.736536
5122,2018-01-01 09:00:00,13440.0,2018.0,1.0,1.0,9.0,5790.325964,7649.674036
5123,2018-01-01 10:00:00,15165.0,2018.0,1.0,1.0,10.0,5745.325964,9419.674036
5124,2018-01-01 11:00:00,15991.0,2018.0,1.0,1.0,11.0,5700.388464,10290.611536
5125,2018-01-01 12:00:00,16323.0,2018.0,1.0,1.0,12.0,5655.388464,10667.611536
5126,2018-01-01 13:00:00,15390.0,2018.0,1.0,1.0,13.0,5610.450964,9779.549036
5127,2018-01-01 14:00:00,10887.0,2018.0,1.0,1.0,14.0,5565.450964,5321.549036
5128,2018-01-01 15:00:00,8326.0,2018.0,1.0,1.0,15.0,5520.450964,2805.549036
5129,2018-01-01 16:00:00,7477.0,2018.0,1.0,1.0,16.0,5475.513464,2001.486536
5130,2018-01-01 17:00:00,5773.0,2018.0,1.0,1.0,17.0,5430.513464,342.486536
5131,2018-01-01 18:00:00,6989.0,2018.0,1.0,1.0,18.0,5385.575964,1603.424036
5132,2018-01-01 19:00:00,7659.0,2018.0,1.0,1.0,19.0,5340.575964,2318.424036
5133,2018-01-01 20:00:00,8720.0,2018.0,1.0,1.0,20.0,5295.575964,3424.424036
5134,2018-01-01 21:00:00,9781.0,2018.0,1.0,1.0,21.0,5250.638464,4530.361536
5135,2018-01-01 22:00:00,8582.0,2018.0,1.0,1.0,22.0,5205.638464,3376.361536
5136,2018-01-01 23:00:00,7933.0,2018.0,1.0,1.0,23.0,5160.700964,2772.299036
5137,2016-01-01 00:00:00,9108.0,2016.0,1.0,1.0,0.0,-1159.600987,10267.600987
5138,2016-01-01 01:00:00,8926.0,2016.0,1.0,1.0,1.0,-1217.600987,10143.600987
5139,2016-01-01 02:00:00,9276.0,2016.0,1.0,1.0,2.0,-1276.600987,10552.600987
5140,2016-01-01 03:00:00,9898.0,2016.0,1.0,1.0,3.0,-1334.600987,11232.600987
5141,2016-01-01 04:00:00,8505.0,2016.0,1.0,1.0,4.0,-1392.600987,9897.600987
5142,2016-01-01 05:00:00,8404.0,2016.0,1.0,1.0,5.0,-1451.600987,9855.600987
...,...,...,...,...,...,...,...,...
13939,2017-01-01 18:00:00,3973.0,2017.0,1.0,1.0,18.0,5102.418756,1129.418756
13940,2017-01-01 19:00:00,4545.0,2017.0,1.0,1.0,19.0,5057.950006,512.950006
13941,2017-01-01 20:00:00,5694.0,2017.0,1.0,1.0,20.0,5013.481256,680.518744
13942,2017-01-01 21:00:00,6186.0,2017.0,1.0,1.0,21.0,4968.981256,1217.018744
13943,2017-01-01 22:00:00,5990.0,2017.0,1.0,1.0,22.0,4924.512506,1065.487494
13944,2017-01-01 23:00:00,6352.0,2017.0,1.0,1.0,23.0,4880.043756,1471.956244
14041,2017-01-06 00:00:00,3401.0,2017.0,1.0,1.0,0.0,6051.841427,2650.841427
14042,2017-01-06 01:00:00,3825.0,2017.0,1.0,1.0,1.0,6006.278927,2181.278927
14043,2017-01-06 02:00:00,4411.0,2017.0,1.0,1.0,2.0,5960.716427,1549.716427
14044,2017-01-06 03:00:00,3988.0,2017.0,1.0,1.0,3.0,5915.216427,1927.216427
14045,2017-01-06 04:00:00,4271.0,2017.0,1.0,1.0,4.0,5869.653927,1598.653927
14046,2017-01-06 05:00:00,5955.0,2017.0,1.0,1.0,5.0,5824.091427,130.908573
14047,2017-01-06 06:00:00,6405.0,2017.0,1.0,1.0,6.0,5778.528927,626.471073
14048,2017-01-06 07:00:00,5203.0,2017.0,1.0,1.0,7.0,5732.966427,529.966427
14049,2017-01-06 08:00:00,4448.0,2017.0,1.0,1.0,8.0,5687.403927,1239.403927
14050,2017-01-06 09:00:00,4950.0,2017.0,1.0,1.0,9.0,5641.903927,691.903927
14051,2017-01-06 10:00:00,5783.0,2017.0,1.0,1.0,10.0,5596.341427,186.658573
14052,2017-01-06 11:00:00,6257.0,2017.0,1.0,1.0,11.0,5550.778927,706.221073
14053,2017-01-06 12:00:00,6765.0,2017.0,1.0,1.0,12.0,5505.216427,1259.783573
14054,2017-01-06 13:00:00,7511.0,2017.0,1.0,1.0,13.0,5459.653927,2051.346073
14055,2017-01-06 14:00:00,7730.0,2017.0,1.0,1.0,14.0,5414.153927,2315.846073
14056,2017-01-06 15:00:00,7119.0,2017.0,1.0,1.0,15.0,5368.591427,1750.408573
14057,2017-01-06 16:00:00,6260.0,2017.0,1.0,1.0,16.0,5323.028927,936.971073
14058,2017-01-06 17:00:00,5129.0,2017.0,1.0,1.0,17.0,5277.466427,148.466427
14059,2017-01-06 18:00:00,4610.0,2017.0,1.0,1.0,18.0,5231.903927,621.903927
14060,2017-01-06 19:00:00,5300.0,2017.0,1.0,1.0,19.0,5186.341427,113.658573
14061,2017-01-06 20:00:00,5551.0,2017.0,1.0,1.0,20.0,5140.841427,410.158573
14062,2017-01-06 21:00:00,5247.0,2017.0,1.0,1.0,21.0,5095.278927,151.721073
14063,2017-01-06 22:00:00,4978.0,2017.0,1.0,1.0,22.0,5049.716427,71.716427
14064,2017-01-06 23:00:00,4709.0,2017.0,1.0,1.0,23.0,5004.153927,295.153927

In [14]:
df_tmp[df_tmp['AE'] > 0].AE.mean()

3555.926713043321